### ISSUE TITLE
e2e testing with protractor (initial implementation)

### ISSUE THREAD

**Issue by Ks89** [Ks89/My-MEAN-website-client#21]
- [x] write tests [initial implementation]
- [x] build config for travisci
- [x] build config for appveyor
- [x] build config for circleci (waiting for both [THIS](https://discuss.circleci.com/t/update-chrome-to-version-59-or-greater-for-circleci-2-0/16323) and [THIS](https://discuss.circleci.com/t/bin-bash-mongo-command-not-found/16218)

**Comment by Ks89** [comment]
Opened an issue to circleci team. I'm waiting for a fix.
```
[22:46:23] I/launcher - Running 1 instances of WebDriver
[22:46:23] I/direct - Using ChromeDriver directly...
[22:46:24] E/launcher - session not created exception: Chrome version must be >= 59.0.3071.0
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.4.0-92-generic x86_64)
[22:46:24] E/launcher - SessionNotCreatedError: session not created exception: Chrome version must be >= 59.0.3071.0
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.4.0-92-generic x86_64)
    at Object.checkLegacyResponse (/home/circleci/project/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/home/circleci/project/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/circleci/project/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:777:24)
    at Function.createSession (/home/circleci/project/node_modules/selenium-webdriver/chrome.js:709:29)
    at Direct.getNewDriver (/home/circleci/project/node_modules/protractor/lib/driverProviders/direct.ts:90:25)
    at Runner.createBrowser (/home/circleci/project/node_modules/protractor/lib/runner.ts:225:39)
    at q.then.then (/home/circleci/project/node_modules/protractor/lib/runner.ts:391:27)
    at _fulfilled (/home/circleci/project/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/circleci/project/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/circleci/project/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/circleci/project/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/home/circleci/project/node_modules/protractor/node_modules/q/q.js:137:13)
[22:46:24] E/launcher - Process exited with error code 199
```

**Comment by Ks89** [comment]
- [x] Before to close this issue, close also #108

**Comment by Ks89** [comment]
initial implementation completed
